Repository accredible/api-documentation, pull requests merged in 2024-06, with the labels that each got.

#69 DGR-464-BE-Add the additional attributes to Apiary
  apiary.apib
Labels: reviewed

#70 Release/v24.12.0
  apiary.apib
Labels: enhancement

#72 Release/v24.12.1
  apiary.apib
Labels: bug

#74 DGR-88: Fix date format discrepancies
  apiary.apib
Labels: reviewed

#73 [DGR-466]- BE - Add the Group cloning API to Apiary
  apiary.apib
Labels: reviewed
